#!/usr/bin/env bash
# Installs and configures Nginx web server

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx (without using systemctl)
service nginx restart
