#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use custom 404 page
sed -i '/server_name _;/a \    error_page 404 /404.html;\n    location = /404.html {\n        root /var/www/html;\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
