#!/usr/bin/env bash
# Script that configures an Ubuntu server with the specified requirements

# Change the localhost IP address to 127.0.0.2
sudo sed -i 's/^127.0.0.1 localhost$/127.0.0.2 localhost/g' /etc/hosts

# Change the IP address for facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
